languageCode = "en-us"
title = "Gabo Esquivel - Software Developer"
googleAnalytics = "UA-33521499-1"
baseurl = "https://gaboesquivel.com"
#canonifyURLs = true
rssLink = "https://feeds.feedburner.com/gaboesquivel"

[params]
  description = "Software Engineer. Blockchain, Decentralized Finance, Distributed Systems, GraphQL, React and React Native"
  email = "contact@gaboesquivel.com"
  dateForm = "Monday, Jan 2, 2006"

[permalinks]
  blog = "blog/:year/:title/"

[markup.goldmark.renderer]
unsafe= true
