languageCode = "en-us"
title = "Gabo Esquivel - Software Developer"
googleAnalytics = "UA-33521499-1"
baseurl = "https://gaboesquivel.com"
#canonifyURLs = true
rssLink = "https://feeds.feedburner.com/gaboesquivel"

[params]
  description = "Software Engineer specialized in Blockchain and Modern Web and JavaScript."
  email = "contact@gaboesquivel.com"
  dateForm = "Monday, Jan 2, 2006"

[permalinks]
  blog = "blog/:year/:title/"
