languageCode = "en-us"
title = "Gabo Esquivel - Software Engineer and Consultant"
theme = "gaboesquivel"
googleAnalytics = "UA-33521499-1"
baseurl = "https://gaboesquivel.com/"
rssLink = "https://feeds.feedburner.com/gaboesquivel"

[params]
  description = "I help companies develop software products and make technical decisions."
  email = "contact@gaboesquivel.com"

[permalinks]
  post = "/:year/:month/:title/"
