languageCode = "en-us"
title = "Gabo Esquivel - Software Engineer"
googleAnalytics = "UA-33521499-1"
baseurl = "/"
#canonifyURLs = true
rssLink = "https://feeds.feedburner.com/gaboesquivel"

[params]
  description = "Open Source and Decentralized Applications. Blockchain, OSS, DevOps. EOS Enthusiast."
  email = "contact@gaboesquivel.com"
  dateForm = "Monday, Jan 2, 2006"

[permalinks]
  blog = "blog/:year/:title/"
