global.jQuery = global.$ = require('jquery')
require('bootstrap')
require('magnific-popup')
global.scrollspy = require('scrollspy')
require('owl.carousel')
require('./libs/jquery.stellar.min')
global.mixitup = require('mixitup')
global.WOW = window.WOW = require('wowjs').WOW
require('./libs/jqBootstrapValidation-1.3.7')
require('./libs/jquery.unveil')

require('./home')
require('./blog')
require('./nav')
require('./contact')
